allDimMethods={'PCA','SimplePCA','ProbPCA','LDA','MDS','SPE','Isomap',...
    'LandmarkIsomap','MVU','FastMVU','KernelPCA','GDA','DiffusionMaps','AutoencoderRBM',...
    'AutoencoderEA','LLE','Laplacian','HessianLLE',...
    'LTSA','Conformal','LPP','NPE','LLTSA','LLC','ManifoldChart','CFA'};
